name: estore
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.3.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#8E6CEF"
  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: fill
flutter:
  assets:
    - assets/images/svg/
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Circular Bold
      fonts:
         - asset: assets/fonts/CircularStd-Bold.ttf

    - family: Circular Book
      fonts:
         - asset: assets/fonts/CircularStd-Book.ttf

    - family: Circular Medium
      fonts:
         - asset: assets/fonts/CircularStd-Medium.ttf
    - family: IconBroken
      fonts:
         - asset: assets/fonts/icons.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
